// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Election struct {
	ID           int32
	Name         string
	ElectionDate pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Party struct {
	ID        int32
	Name      string
	ShortName pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PartyStance struct {
	ID         int32
	PartyID    int32
	QuestionID int32
	Stance     int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Question struct {
	ID           int32
	ElectionID   int32
	Title        string
	QuestionText string
	Description  pgtype.Text
	DisplayOrder int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
