sql:
    - engine: postgresql
      gen:
        go:
            out: db
            sql_package: "pgx/v5"
            package: db
      queries:
        - ./sql/query.sql
      schema:
        - "./sql/schema.sql"
version: "2"
